project_id = "lfagpktbjzlyylbuwckk"

[functions.upload-audio]
verify_jwt = false

[functions.list-teachers]
verify_jwt = false

[functions.fetch-airtable]
verify_jwt = false

[functions.list-classes]
verify_jwt = false

