-- Fix critical security issue: Make audio-submissions bucket private
-- This protects student voice recordings and complies with GDPR
UPDATE storage.buckets 
SET public = false 
WHERE id = 'audio-submissions';

-- Drop existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "Service role can manage audio files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can view audio via signed URLs" ON storage.objects;

-- Add RLS policy: Service role (edge functions) can manage all audio files
CREATE POLICY "Service role can manage audio files"
ON storage.objects
FOR ALL
TO service_role
USING (bucket_id = 'audio-submissions')
WITH CHECK (bucket_id = 'audio-submissions');

-- Add RLS policy: Authenticated users can view audio files
-- This allows teachers to access files via signed URLs generated by edge functions
CREATE POLICY "Authenticated users can view audio via signed URLs"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'audio-submissions');